### ISSUE TITLE
Can't install npm -i and watch, 

### ISSUE THREAD

**Issue by alwismt** [mshossain110/LaravelAdmin#5]
Which Os you use for this projects, I tried with Cent Os, Kali Linux and parrot os

Something Wrong with project lot of errors showing when use npm

**Comment by mshossain110** [comment]
I use docker with Linux ubuntu on my mac os. can you share errors so I can understand and solve it.

**Comment by alwismt** [comment]
This is Centos Errors
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/bin/npm', 'run', 'watch' ]
2 info using npm@3.10.10
3 info using node@v6.17.1
4 verbose run-script [ 'prewatch', 'watch', 'postwatch' ]
5 info lifecycle @~prewatch: @
6 silly lifecycle @~prewatch: no script for prewatch, continuing
7 info lifecycle @~watch: @
8 verbose lifecycle @~watch: unsafe-perm in lifecycle true
9 verbose lifecycle @~watch: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/drive/public_html/LaravelDrive/node_modules/.bin:/usr/bin:/usr/local/cpanel/3rdparty/lib/path-bin:/usr/local/jdk/bin:/usr/kerberos/sbin:/usr/kerberos/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/X11R6/bin:/usr/local/bin:/usr/X11R6/bin:/root/bin:/opt/bin:/opt/cpanel/composer/bin:/root/bin
10 verbose lifecycle @~watch: CWD: /home/drive/public_html/LaravelDrive
11 silly lifecycle @~watch: Args: [ '-c', 'npm run development -- --watch' ]
12 silly lifecycle @~watch: Returned: code: 1  signal: null
13 info lifecycle @~watch: Failed to exec watch script
14 verbose stack Error: @ watch: `npm run development -- --watch`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:920:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
15 verbose pkgid @
16 verbose cwd /home/drive/public_html/LaravelDrive
17 error Linux 3.10.0-1062.el7.x86_64
18 error argv "/usr/bin/node" "/bin/npm" "run" "watch"
19 error node v6.17.1
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error @ watch: `npm run development -- --watch`
22 error Exit status 1
23 error Failed at the @ watch script 'npm run development -- --watch'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the  package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run development -- --watch
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by alwismt** [comment]
If you can upload project after npm installed, Thats pretty, Cause now npm not support for lot of os, :(

**Comment by mshossain110** [comment]
can you update your node and npm version? 
currently, installed  
node v6.17.1
npm  v3.10.10

please update your node and npm

**Comment by alwismt** [comment]
Sorry! Cent OS not support to update node and npm this is the version they support, I'm using German VPS with centOs, I can only access it thought vnc, 

Anyway I have Kali Linux 2020 latest version on my PC, 
```
Node -v
v10.19.0
npm -v
6.14.4
```
`Using Lamp with Xampp Php version 7.2.`

This is Kali Linux errors when hit `npm run watch` , 

![Screenshot from 2020-05-08 18-58-18](https://user-images.githubusercontent.com/49513212/81410562-93bfdf00-915e-11ea-9266-aa3504edc360.png)


This is view not Showing Loging
![Screenshot from 2020-05-08 18-59-08](https://user-images.githubusercontent.com/49513212/81410653-b7832500-915e-11ea-85ee-56224055be89.png)

**Comment by alwismt** [comment]
Also Your demo site is not working anymore :(

**Comment by mshossain110** [comment]
1. plyr issue is solved. please pull and run commend (`npm i & npm run watch`) again
2. stared.vue file has an issue. I will solve it. ( need time)
3. The login page does not have any issue (I am not finding this issue) it may possible for your URL. you should run in any server. `php artisan serve` can help you in your local server.

4. The demo server is inactive now. I need to renew the server.

**Comment by alwismt** [comment]
yeah! plyr is working now but still have vue compiling issue, `php artisan serve` thats okay but, When we host we rename  artisan.php to index.php, So its should be work with normally without `php artisan serve`this code :)

**Comment by LeonardoPastaDigital** [comment]
Hello, 
I am experiencing the same issue, just downloaded the project and I am trying to install it, but the login page doesn't show any kind of login form.
Also when I try to run npm i it just gives me errors.

I am using vagrant with homestead to host my laravel projects.

Could you please help me?

Thanks in advance :)

![image](https://user-images.githubusercontent.com/65964474/82915086-34d4d500-9f68-11ea-9721-79b9cc17330d.png)

![image](https://user-images.githubusercontent.com/65964474/82915215-6057bf80-9f68-11ea-85b9-ed8dead59d2a.png)

**Comment by mshossain110** [comment]
@LeonardoPastaDigital you make a command. 

it will be `npm install `

**Comment by LeonardoPastaDigital** [comment]
@mshossain110 I've done it, didn't work, the only work around that i could find was use Laragon instead
